name: CI

on:
    push:
        branches:
            - huyxuhao/test_github_action
    pull_request:
        branches:
            - huyxuhao/test_github_action

jobs:
    build:
        runs-on: ubuntu-latest
        steps:            
            - name: Checkout
              uses: actions/checkout@v4
            - name: Check disk space            
              run: df -h